### ISSUE TITLE
entity evaluation gives error  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by NahedMahmoud1** [RasaHQ/nlu-hyperopt#6] opened 2019-05-08 11:44 UTC
Why it gives me this error ?
and what is the meaning for the "no entity"
hint I deleted all the entities from the testing data to test if it will give the same error.
Thanks in advance
![Screen Shot 2019-05-08 at 1 43 41 PM](https://user-images.githubusercontent.com/38400841/57372969-69c48d00-7197-11e9-9db1-40976c19187d.png)

**Comment by crodriguez1a** [comment] 2020-05-28 22:23
@NahedMahmoud1 Not sure if this is still being tracked. This is could be occurring when `metric_result` is defined [here](https://github.com/RasaHQ/nlu-hyperopt/blob/master/nlu_hyperopt/optimization.py#L69). Seems there should be a null check on `intent_evaluation` before attempting to access its members.

I haven't come across the root cause yet, but I'll post again if I do (if at all helpful to anyone else). :happy:

**Comment by crodriguez1a** [comment] 2020-05-29 14:13
@NahedMahmoud1 In my case, it turned out to be that my training and validation files were not formatted properly and no intents were discovered during the evaluation step [here](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/test.py#L1828). Once I addressed that, I no longer came across this issue.

**Comment by indam23** [comment] 2022-08-08 18:56
Closing as resolved

**Closed by indam23** 2022-08-08 18:56 UTC
